### ISSUE TITLE
Feel free to cannibalize this code!

### ISSUE THREAD

**Issue by sarciszewski** [SammyK/php-src-csprng#1]
I wrote something for my own uses, feel free to cannibalize bits of it for this project so I and others can use this as a dependency. (Please review it first of course.)

`random_bytes()`:
- https://github.com/resonantcore/lib/blob/develop/src/Secure.php#L71-L101

`random_int()`:
- https://github.com/resonantcore/lib/blob/develop/src/Secure.php#L41-L69
- https://github.com/resonantcore/lib/blob/develop/src/Secure.php#L148-L161

**Comment by SammyK** [comment]
Thanks for the tip @sarciszewski! The whole [bytes to int](https://github.com/resonantcore/lib/blob/develop/src/Secure.php#L148-L161) stuff will be helpful as I try to convert these into C. :)

PS: It was because of your PR in the Facebook PHP SDK that I started down this road - thanks. :)
